// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Feedback - Create feedback
type Feedback struct {
	FeedbackJSON map[string]interface{} `json:"feedback_json,omitempty"`
	GenerationID *string                `json:"generation_id,omitempty"`
	Task         *string                `json:"task,omitempty"`
}
